# Generated by Django 5.2.8 on 2025-11-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_lead_status_alter_lead_lead_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('area_sqft', models.CharField(blank=True, max_length=50, null=True)),
                ('bhk', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('SELLER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='whatsapp.lead')),
            ],
        ),
    ]
