# Generated by Django 5.2.8 on 2025-11-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='segment',
            field=models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('UNQUALIFIED', 'Unqualified')], default='NEW', max_length=20),
        ),
    ]
