# Generated by Django 5.2.8 on 2025-11-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_lead_rejection_reason_lead_score_lead_segment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='segment',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('ACTIVE', 'Active'), ('PROSPECT', 'Prospect'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=10),
        ),
    ]
